import {
  app,
  BrowserWindow,
  globalShortcut,
  clipboard,
  ipcMain,
  ipcRenderer,
} from "electron";
import ReactDOM from "react-dom";
import clipboardListener from "clipboard-event";

require("dotenv").config();
require("@electron/remote/main").initialize();

// This allows TypeScript to pick up the magic constant that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  // eslint-disable-line global-require
  app.quit();
}

const createWindow = (): void => {
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    title: "Expt",
    icon: "./logo.png",
    titleBarStyle: "hidden",
    resizable: false,
    frame: false,
    transparent: true,
    webPreferences: {
      //@ts-ignore
      enableRemoteModule: true,
      contextIsolation: false,
      nodeIntegration: true,
      devTools: true,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  // mainWindow.webContents.openDevTools();
  require("@electron/remote/main").enable(mainWindow.webContents);

  //Global Events
  ipcMain.on("min", (event, arg) => {
    mainWindow.minimize();
  });
  ipcMain.on("close", (event, arg) => {
    app.quit();
  });
  ipcMain.on("copy", (event, arg) => {
    clipboard.writeText(arg);
  });

  clipboardListener.startListening();
  clipboardListener.on("change", () => {
    if (!mainWindow.isFocused()) {
      const text = clipboard.readText();
      mainWindow.webContents.send("clippy", text);
    }
  });
};

// initialization, create browser windows.
app.on("ready", createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});
